//! Full-world equirectangular land mask, with a single aspect-preserving fit.
//! The bundled Natural Earth mask is generated by scripts/render-map.mjs.

const COLUMNS: usize = 240;
const ROWS: usize = 120;
const LAND: &[u8; COLUMNS * ROWS / 8] = include_bytes!("../assets/maps/world-land.bin");

pub fn dots() -> Vec<(f64, f64)> {
    (0..COLUMNS * ROWS)
        .filter(|index| LAND[index / 8] & (1 << (index % 8)) != 0)
        .map(|index| {
            (
                ((index % COLUMNS) as f64 + 0.5) / COLUMNS as f64,
                ((index / COLUMNS) as f64 + 0.5) / ROWS as f64,
            )
        })
        .collect()
}

#[derive(Debug)]
pub struct MapRect {
    pub left: f64,
    pub top: f64,
    pub width: f64,
    pub height: f64,
}

pub fn fit(width: f64, height: f64) -> MapRect {
    let width = width.max(0.0);
    let height = height.max(0.0);
    // Always contain the whole world, with equal margins on opposite sides.
    // No minimum map size: that was cropping small windows and shifting the map.
    let map_width = (width * 0.92).min(height * 0.84 * 2.0);
    let map_height = map_width / 2.0;
    MapRect {
        left: (width - map_width) / 2.0,
        top: (height - map_height) / 2.0,
        width: map_width,
        height: map_height,
    }
}
